const initialGameState = {
  power: 5,
  tickSpeed: 100,
  influxPerSecond: 0,
  purchasables: [
    {
      id: 'zombie',
      name: 'Zombie',
      description: 'A speechless revenant.',
      purchased: true,
      quantity: 0,
      outfluxPerSecond: 0,
      ctaText: 'Raise a Zombie',
      nextCost: 3,
      baseCost: 3.738,
      costCoefficient: 1.07,
      baseProductivityPerSecond: 1.67,
    },
    {
      id: 'library',
      name: 'Evil Library',
      description:
        'Knowledge is dangerous. The people who control that knowledge are even more dangerous.',
      purchased: false,
      quantity: 0,
      outfluxPerSecond: 0,
      ctaText: 'Assemble a Library',
      nextCost: 60,
      baseCost: 60,
      costCoefficient: 1.15,
      baseProductivityPerSecond: 20,
    },
    {
      id: 'dungeon',
      name: 'Dungeons',
      description: 'A quiet place to do dark business.',
      purchased: false,
      quantity: 0,
      outfluxPerSecond: 0,
      ctaText: 'Craft a Dungeon',
      nextCost: 720,
      baseCost: 720,
      costCoefficient: 1.14,
      baseProductivityPerSecond: 90,
    },
    {
      id: 'city',
      name: 'City of the Dead',
      description: 'Where once was life and movement, all is dark and waiting.',
      purchased: false,
      quantity: 0,
      outfluxPerSecond: 0,
      ctaText: 'Convert a city',
      nextCost: 8640,
      baseCost: 8640,
      costCoefficient: 1.13,
      baseProductivityPerSecond: 360,
    },
    {
      id: 'army',
      name: 'Armies of the Dead',
      description: 'A wall of undead as far as the eye can see.',
      purchased: false,
      quantity: 0,
      outfluxPerSecond: 0,
      ctaText: 'Raise an Army',
      nextCost: 103680,
      baseCost: 103680,
      costCoefficient: 1.12,
      baseProductivityPerSecond: 2160,
    },
  ],
};

export default initialGameState;
